[project]
name = "gringotts-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "google-auth>=2.38.0",
    "pydantic>=2.11.3",
    "pydantic-settings>=2.8.1",
    "python-jose[cryptography]>=3.4.0",
    "requests-toolbelt>=1.0.0",
]

[dependency-groups]
dev = [
    "isort>=6.0.1",
    "ruff>=0.11.5",
]
